BASE=../..

include $(BASE)/rule/def.mk

O_TARGET=am_teletext
am_teletext_SRCS=VTCharacterSet.c VTCommon.c VTDecoder.c VTDrawer.c VTMosaicGraphics.c VTTeletext.c VTTopText.c am_mw_teletext.c


include $(BASE)/rule/rule.mk
