BASE=../..

include $(BASE)/rule/def.mk

APP_TARGET=am_subtitle_test
am_subtitle_test_SRCS=am_subtitle_test.c
am_subtitle_test_LIBS=../../am_adp/am_adp ../../am_mw/am_mw 

include $(BASE)/rule/rule.mk
