BASE=../..

include $(BASE)/rule/def.mk

APP_TARGET=am_teletext_test
am_teletext_test_SRCS=am_teletext_test.c
am_teletext_test_LIBS=../../am_adp/am_adp ../../am_mw/am_mw 



include $(BASE)/rule/rule.mk
